<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 14 GLM - Logistic Regression | STAT462 Lab Book 2024</title>
<meta name="author" content="Dr Helen Greatrex">
<meta name="description" content="Logistic regression is a method used when we’re dealing with categorical dependent variables. It’s particularly useful for predicting the probability of an event occurring, fitting data to a...">
<meta name="generator" content="bookdown 0.37 with bs4_book()">
<meta property="og:title" content="Chapter 14 GLM - Logistic Regression | STAT462 Lab Book 2024">
<meta property="og:type" content="book">
<meta property="og:description" content="Logistic regression is a method used when we’re dealing with categorical dependent variables. It’s particularly useful for predicting the probability of an event occurring, fitting data to a...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 14 GLM - Logistic Regression | STAT462 Lab Book 2024">
<meta name="twitter:description" content="Logistic regression is a method used when we’re dealing with categorical dependent variables. It’s particularly useful for predicting the probability of an event occurring, fitting data to a...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.6.1/transition.js"></script><script src="libs/bs3compat-0.6.1/tabs.js"></script><script src="libs/bs3compat-0.6.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><script src="libs/plotly-binding-4.10.3/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">STAT462 Lab Book 2024</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome to STAT-462!</a></li>
<li><a class="" href="FAQ.html">Course FAQ</a></li>
<li><a class="" href="WhatIsR.html">What are R and R-Studio?</a></li>
<li><a class="" href="Setup_Desktop.html">Installing R/R-Studio</a></li>
<li><a class="" href="Setup_UpdateDesktop.html">Updating R/R-Studio</a></li>
<li><a class="" href="Setup_Online.html">Posit Cloud Online</a></li>
<li class="book-part">.</li>
<li class="book-part">LAB INSTRUCTIONS</li>
<li><a class="" href="Help.html">HELP!</a></li>
<li><a class="" href="Lab_1.html">Lab 1</a></li>
<li><a class="" href="Lab_2.html">Lab 2</a></li>
<li><a class="" href="Lab_3.html">Lab 3</a></li>
<li><a class="" href="Lab_4.html">Lab 4</a></li>
<li><a class="" href="Lab_5.html">Lab 5A</a></li>
<li><a class="" href="Lab_5B.html">Lab 5B</a></li>
<li><a class="" href="lab-6.html">Lab 6</a></li>
<li><a class="" href="final-project.html">Final Project</a></li>
<li class="book-part">.</li>
<li class="book-part">TUTORIALS</li>
<li><a class="" href="T1_Projects.html"><span class="header-section-number">1</span> Projects/Starting a lab</a></li>
<li><a class="" href="T2_Libraries.html"><span class="header-section-number">2</span> Libraries/Packages</a></li>
<li><a class="" href="T3_Markdown.html"><span class="header-section-number">3</span> R-Markdown</a></li>
<li><a class="" href="T4_ReadingData.html"><span class="header-section-number">4</span> Reading in data</a></li>
<li><a class="" href="probability-distributions.html"><span class="header-section-number">5</span> Probability distributions</a></li>
<li><a class="" href="T6_plots.html"><span class="header-section-number">6</span> Plots</a></li>
<li><a class="" href="correlation.html"><span class="header-section-number">7</span> Correlation</a></li>
<li><a class="" href="T8_regression.html"><span class="header-section-number">8</span> Regression</a></li>
<li><a class="" href="T9_wrangling.html"><span class="header-section-number">9</span> Data Wrangling</a></li>
<li><a class="" href="T10_diagnostics.html"><span class="header-section-number">10</span> Assessing LINE</a></li>
<li><a class="" href="outliers-high-leverage-influential-points.html"><span class="header-section-number">11</span> Outliers, high leverage &amp; influential points</a></li>
<li><a class="" href="confidence-and-prediction-intervals.html"><span class="header-section-number">12</span> Confidence and Prediction Intervals</a></li>
<li><a class="" href="S.Tutorial_Transformations.html"><span class="header-section-number">13</span> Transformations</a></li>
<li><a class="active" href="S.Tutorial_GLM.html"><span class="header-section-number">14</span> GLM - Logistic Regression</a></li>
<li><a class="" href="basic-model-comparisons.html"><span class="header-section-number">15</span> Basic model comparisons</a></li>
<li><a class="" href="multiple-regression-model-fitting.html"><span class="header-section-number">16</span> Multiple regression &amp; model fitting</a></li>
<li><a class="" href="finding-the-optimal-model.html"><span class="header-section-number">17</span> Finding the “optimal model”</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="S.Tutorial_GLM" class="section level1" number="14">
<h1>
<span class="header-section-number">14</span> GLM - Logistic Regression<a class="anchor" aria-label="anchor" href="#S.Tutorial_GLM"><i class="fas fa-link"></i></a>
</h1>
<p>Logistic regression is a method used when we’re dealing with categorical dependent variables. It’s particularly useful for predicting the probability of an event occurring, fitting data to a logistic curve. While simple linear regression predicts continuous outcomes, logistic regression focuses on probabilities between 0 and 1, making it perfect for scenarios like yes/no or true/false.</p>
<p>Logistic regression is a Generalized Linear Model (GLM), which expands Simple Linear Regression to handle non-normally distributed response variables. GLMs accommodate various response distributions, like binomial (for logistic regression), Poisson, or gamma distributions, making them adaptable to different data types. Within the GLM framework, logistic regression models the relationship between categorical outcomes and predictors by connecting the linear combination of predictors to the log odds of the outcome.</p>
<div id="great-r-tutorial" class="section level2" number="14.1">
<h2>
<span class="header-section-number">14.1</span> Great R Tutorial<a class="anchor" aria-label="anchor" href="#great-r-tutorial"><i class="fas fa-link"></i></a>
</h2>
<p><a href="https://bookdown.org/jefftemplewebb/IS-6489/logistic-regression.html" class="uri">https://bookdown.org/jefftemplewebb/IS-6489/logistic-regression.html</a></p>
</div>
<div id="setting-up-the-dataexample" class="section level2" number="14.2">
<h2>
<span class="header-section-number">14.2</span> Setting up the data/example<a class="anchor" aria-label="anchor" href="#setting-up-the-dataexample"><i class="fas fa-link"></i></a>
</h2>
<div id="setting-up-categorical-columns" class="section level3" number="14.2.1">
<h3>
<span class="header-section-number">14.2.1</span> Setting up categorical columns<a class="anchor" aria-label="anchor" href="#setting-up-categorical-columns"><i class="fas fa-link"></i></a>
</h3>
<p>For example, using the titanic dataset from the DALEX package, lets imagine I want to assess whether richer/poorer people were more likely to die on the ship Titanic:</p>
<ul>
<li>
<u><strong>Dataset</strong></u>: The titanic data is a complete list of passengers and crew members on the RMS Titanic. It includes a variable indicating whether a person did survive the sinking of the RMS Titanic on April 15, 1912.</li>
<li>
<strong>Object of analysis</strong>: ADULT PASSENGERS person on the ship titanic - I need to filter the data to achieve this and remove staff and children.</li>
<li>
<strong>Response variable:</strong> Survival (Yes/No)
<ul>
<li>To make sure that R understands that this is categorical data (rather than say names/random text), we use the <code><a href="https://rdrr.io/r/base/factor.html">as.factor()</a></code> command to force R to see if as binary data.</li>
</ul>
</li>
<li>
<strong>Predictor:</strong> The fare paid to board the titanic.</li>
</ul>
<div id="data-summary" class="section level4" number="14.2.1.1">
<h4>
<span class="header-section-number">14.2.1.1</span> Data summary<a class="anchor" aria-label="anchor" href="#data-summary"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb274"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"titanic"</span>, package <span class="op">=</span> <span class="st">"DALEX"</span><span class="op">)</span></span>
<span><span class="va">ship_survival</span> <span class="op">&lt;-</span> <span class="va">titanic</span></span>
<span>   </span>
<span><span class="co"># I'm going to force the response to be a factor</span></span>
<span><span class="va">ship_survival</span><span class="op">$</span><span class="va">survived</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">titanic</span><span class="op">$</span><span class="va">survived</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="va">ship_survival</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:unnamed-chunk-1">Table 14.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">ship_survival</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">2207</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">9</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">factor</td>
<td align="left">5</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">4</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: factor</strong></p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="14%">
<col width="10%">
<col width="14%">
<col width="8%">
<col width="9%">
<col width="42%">
</colgroup>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">mal: 1718, fem: 489</td>
</tr>
<tr class="even">
<td align="left">class</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="left">FALSE</td>
<td align="right">7</td>
<td align="left">3rd: 709, vic: 431, 1st: 324, eng: 324</td>
</tr>
<tr class="odd">
<td align="left">embarked</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="left">FALSE</td>
<td align="right">4</td>
<td align="left">Sou: 1616, Che: 271, Bel: 197, Que: 123</td>
</tr>
<tr class="even">
<td align="left">country</td>
<td align="right">81</td>
<td align="right">0.96</td>
<td align="left">FALSE</td>
<td align="right">48</td>
<td align="left">Eng: 1125, Uni: 264, Ire: 137, Swe: 105</td>
</tr>
<tr class="odd">
<td align="left">survived</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">no: 1496, yes: 711</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: numeric</strong></p>
<div class="inline-table"><table style="width:100%;" class="table table-sm">
<colgroup>
<col width="16%">
<col width="11%">
<col width="16%">
<col width="7%">
<col width="7%">
<col width="5%">
<col width="4%">
<col width="7%">
<col width="7%">
<col width="8%">
<col width="7%">
</colgroup>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">2</td>
<td align="right">1.00</td>
<td align="right">30.44</td>
<td align="right">12.16</td>
<td align="right">0.17</td>
<td align="right">22</td>
<td align="right">29.00</td>
<td align="right">38.00</td>
<td align="right">74.00</td>
<td align="left">▁▇▆▂▁</td>
</tr>
<tr class="even">
<td align="left">fare</td>
<td align="right">26</td>
<td align="right">0.99</td>
<td align="right">19.77</td>
<td align="right">43.40</td>
<td align="right">0.00</td>
<td align="right">0</td>
<td align="right">7.15</td>
<td align="right">20.11</td>
<td align="right">512.06</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">sibsp</td>
<td align="right">10</td>
<td align="right">1.00</td>
<td align="right">0.30</td>
<td align="right">0.84</td>
<td align="right">0.00</td>
<td align="right">0</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">8.00</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">parch</td>
<td align="right">10</td>
<td align="right">1.00</td>
<td align="right">0.23</td>
<td align="right">0.69</td>
<td align="right">0.00</td>
<td align="right">0</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">9.00</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<div id="filtering-data-exploratory-plots" class="section level3" number="14.2.2">
<h3>
<span class="header-section-number">14.2.2</span> Filtering data &amp; exploratory plots<a class="anchor" aria-label="anchor" href="#filtering-data-exploratory-plots"><i class="fas fa-link"></i></a>
</h3>
<p>I am first going to remove any children from the dataset and any staff (AKA fare = 0), along with the four millionaires that I feel are special cases (e.g. they paid over three times the amount everyone else did)</p>
<div class="sourceCode" id="cb275"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ship_survival</span> <span class="op">&lt;-</span> <span class="va">ship_survival</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">ship_survival</span><span class="op">$</span><span class="va">fare</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span>,<span class="op">]</span></span>
<span><span class="va">ship_survival</span> <span class="op">&lt;-</span> <span class="va">ship_survival</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">ship_survival</span><span class="op">$</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">21</span><span class="op">)</span>,<span class="op">]</span></span>
<span><span class="va">ship_survival</span> <span class="op">&lt;-</span> <span class="va">ship_survival</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">ship_survival</span><span class="op">$</span><span class="va">fare</span> <span class="op">&lt;</span> <span class="fl">300</span><span class="op">)</span>,<span class="op">]</span></span></code></pre></div>
<p>If we only have one predictor, we can use plots like this to get a sense of the impact on our binary response. I included “jittered” data AKA the points are scattered around a little to make them visible. This code comes from the ggplot2 package, so remember to put that in your library code chunk.</p>
<div class="sourceCode" id="cb276"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ship_survival</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">survived</span>, y <span class="op">=</span> <span class="va">fare</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span>outlier.shape <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>size<span class="op">=</span><span class="fl">.7</span>,alpha<span class="op">=</span><span class="fl">.5</span>,color<span class="op">=</span><span class="st">"blue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-3-1.png" width="672"></div>
<p>Or similarly (but flipped). This code comes from the <strong>ggstatsplot</strong> library/package, so remember to load that first.</p>
<div class="sourceCode" id="cb277"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://indrajeetpatil.github.io/ggstatsplot/">ggstatsplot</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://indrajeetpatil.github.io/ggstatsplot/reference/ggbetweenstats.html">ggbetweenstats</a></span><span class="op">(</span><span class="va">ship_survival</span>,y<span class="op">=</span><span class="va">fare</span>,x<span class="op">=</span><span class="va">survived</span>,results.subtitle<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-4-1.png" width="672"></div>
</div>
<div id="fiting-a-logistic-model" class="section level3" number="14.2.3">
<h3>
<span class="header-section-number">14.2.3</span> Fiting a logistic model<a class="anchor" aria-label="anchor" href="#fiting-a-logistic-model"><i class="fas fa-link"></i></a>
</h3>
<p>Fitting a model is easy - as it’s very similar to simple linear models:</p>
<ul>
<li>Instead of <code>lm</code> (linear model), we need the <code>glm</code> command</li>
<li>We also need an extra part to tell R which type of linear model we want. In our case (for binary data), we need <code>family=binomial(link='logit')</code>
</li>
</ul>
<div class="sourceCode" id="cb278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">model.logistic</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">survived</span> <span class="op">~</span> <span class="va">fare</span>, data<span class="op">=</span><span class="va">ship_survival</span>, </span>
<span>                      family<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link<span class="op">=</span><span class="st">'logit'</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p><br><br></p>
</div>
<div id="model-summary" class="section level3" number="14.2.4">
<h3>
<span class="header-section-number">14.2.4</span> Model summary<a class="anchor" aria-label="anchor" href="#model-summary"><i class="fas fa-link"></i></a>
</h3>
<p><strong>THE OLSRR PACKAGE WILL NO LONGER WORK (it’s only set up for lm).</strong> So we are back to the standard summary command.</p>
<div class="sourceCode" id="cb279"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = survived ~ fare, family = binomial(link = "logit"), 
##     data = ship_survival)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.92126    0.09134 -10.086  &lt; 2e-16 ***
## fare         0.01311    0.00185   7.087 1.37e-12 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1225.2  on 919  degrees of freedom
## Residual deviance: 1157.4  on 918  degrees of freedom
## AIC: 1161.4
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<ul>
<li><p>In the output above, the top part is the call, this is R reminding us what the model we ran and the options we selected.</p></li>
<li><p>The next part of the output shows the coefficients, their standard errors, the z-statistic (sometimes called a Wald z-statistic), and the associated p-values.</p></li>
<li><p>Below the table of coefficients are fit indices, including the null and deviance residuals and the AIC. Later we show an example of how you can use these values to help assess model fit.</p></li>
</ul>
<p>The coefficients themselves are expressed in terms of LOG-ODDS (because this was the transformation we applied).</p>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># coefficient in terms of Log-odds</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>Coefficient_logodds <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##             Coefficient_logodds        2.5 %     97.5 %
## (Intercept)         -0.92125477 -1.102666988 -0.7443837
## fare                 0.01311288  0.009642147  0.0169076</code></pre>
<p>You can also use the exponential command to interpret the output as ODDS-RATIOS, or as the percentage change in odds. We can combine this with confidence intervals and our coefficients using this code.</p>
<div class="sourceCode" id="cb283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># coefficient in terms of odds. Note the exp e.g. we are applying an exponential</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>Coefficient_Odds <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##             Coefficient_Odds     2.5 %   97.5 %
## (Intercept)        0.3980193 0.3319845 0.475027
## fare               1.0131992 1.0096888 1.017051</code></pre>
<div id="interpretation-in-terms-of-log-odds." class="section level4" number="14.2.4.1">
<h4>
<span class="header-section-number">14.2.4.1</span> Interpretation in terms of log odds.<a class="anchor" aria-label="anchor" href="#interpretation-in-terms-of-log-odds."><i class="fas fa-link"></i></a>
</h4>
<p>To interpret, for every one pound increase in fare, the <em>log odds</em> of survival are likely to <strong>increase</strong> between 0.0096421 and 0.0169076.</p>
<p><br></p>
</div>
<div id="interpretation-in-terms-of-odds" class="section level4" number="14.2.4.2">
<h4>
<span class="header-section-number">14.2.4.2</span> Interpretation in terms of odds:<a class="anchor" aria-label="anchor" href="#interpretation-in-terms-of-odds"><i class="fas fa-link"></i></a>
</h4>
<p>We take the exponential of the log odds (see code above). In our new unit, the slope coefficient for fare is 1.0131992 in terms of ODDS.</p>
<ul>
<li>This means that for each unit increase in fare, the odds of survival are multiplied by approximately 1.0131992.</li>
</ul>
<p>In other words, for every one-year increase in fare, the odds of survival increase by a factor of approximately 1.0131992.</p>
<p><br></p>
</div>
<div id="interpretation-in-terms-of-percentage-change" class="section level4" number="14.2.4.3">
<h4>
<span class="header-section-number">14.2.4.3</span> Interpretation in terms of percentage change:<a class="anchor" aria-label="anchor" href="#interpretation-in-terms-of-percentage-change"><i class="fas fa-link"></i></a>
</h4>
<p>To express the coefficient in terms of percentage change, we subtract 1 from the coefficient in odds, multiply by 100, and interpret the result as a percentage change in the odds:</p>
<p>(Odds Ratio−1)×100=( 1.0131992 −1)×100= 1.3199234 %</p>
<p>So, the coefficient for fare represents an increase in the ODDS of survival by approximately 1.32% for each one-pound increase in fare.</p>
<p>To see more examples of this, see here:<br><a href="https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/" class="uri">https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/</a></p>
</div>
</div>
<div id="predicting-new-values-and-visualising-results" class="section level3" number="14.2.5">
<h3>
<span class="header-section-number">14.2.5</span> Predicting new values and visualising results<a class="anchor" aria-label="anchor" href="#predicting-new-values-and-visualising-results"><i class="fas fa-link"></i></a>
</h3>
<p>For prediction, we can do exactly the same as with the lm case e.g. use predict and fitted.</p>
<div class="sourceCode" id="cb285"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ship_survival</span> <span class="op">&lt;-</span> <span class="va">ship_survival</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">ship_survival</span><span class="op">$</span><span class="va">fare</span><span class="op">)</span><span class="op">==</span><span class="cn">FALSE</span>,<span class="op">]</span></span>
<span></span>
<span><span class="va">ship_survival</span><span class="op">$</span><span class="va">modelled_probability</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">model.logistic</span>,</span>
<span>                                             newdata<span class="op">=</span><span class="va">ship_survival</span><span class="op">$</span><span class="va">fare</span><span class="op">)</span></span></code></pre></div>
<p>and this code might help you visualise results (you need to run the prediction bit first.)</p>
<div class="sourceCode" id="cb286"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ship_survival</span><span class="op">$</span><span class="va">type_num</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">ship_survival</span><span class="op">$</span><span class="va">survived</span> <span class="op">==</span> <span class="st">"yes"</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ship_survival</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">fare</span>,<span class="va">type_num</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha<span class="op">=</span><span class="fl">0.5</span>,size<span class="op">=</span><span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">stat_smooth</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">fare</span>, <span class="va">modelled_probability</span><span class="op">)</span>, se <span class="op">=</span> <span class="cn">F</span>,lwd<span class="op">=</span><span class="fl">.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Probability of survival"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"Probability of surviving the titanic based on fare paid"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-10-1.png" width="672"></div>
<p>You can see that the line isn’t straight - there are fare brackets that really impact your survival rate, whereas people who paid fares greater 200 pounds saw the relationship level out (AKA they are already first class).</p>
<p><br><br></p>
</div>
<div id="wald-test-for-significance" class="section level3" number="14.2.6">
<h3>
<span class="header-section-number">14.2.6</span> Wald test for significance<a class="anchor" aria-label="anchor" href="#wald-test-for-significance"><i class="fas fa-link"></i></a>
</h3>
<p>You interpret the significance of the coefficients the same way as your T-test with lm. So we look at the p value in the coefficients table:</p>
<div class="sourceCode" id="cb287"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = survived ~ fare, family = binomial(link = "logit"), 
##     data = ship_survival)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.92126    0.09134 -10.086  &lt; 2e-16 ***
## fare         0.01311    0.00185   7.087 1.37e-12 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1225.2  on 919  degrees of freedom
## Residual deviance: 1157.4  on 918  degrees of freedom
## AIC: 1161.4
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<blockquote>
<p><em>From the summary, you can see that if the true population had no link between fare and survival (our H0), then a tiny 1.37x10^-12 proportion of randomly selected samples would have a slope as steep as our sample. So in this case, I think there is a lot of evidence to suggest that we can reject H0 and suggest that fare paid significantly impacted the survival rate of adult Titanic passengers.</em></p>
</blockquote>
<p><br><br></p>
</div>
<div id="goodness-of-fit" class="section level3" number="14.2.7">
<h3>
<span class="header-section-number">14.2.7</span> Goodness of fit<a class="anchor" aria-label="anchor" href="#goodness-of-fit"><i class="fas fa-link"></i></a>
</h3>
<p>For this, we can use the from the NEW blorr package (AKA you have to go to the app store and install it, then add library(blorr) to your library code chunk)</p>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://blorr.rsquaredacademy.com/">blorr</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://blorr.rsquaredacademy.com/reference/blr_test_hosmer_lemeshow.html">blr_test_hosmer_lemeshow</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span></span></code></pre></div>
<pre><code>##            Partition for the Hosmer &amp; Lemeshow Test            
## --------------------------------------------------------------
##                         def = 1                 def = 0        
## Group    Total    Observed    Expected    Observed    Expected 
## --------------------------------------------------------------
##   1       129        32        39.18         97        89.82   
##   2       88         16        26.77         72        61.23   
##   3       62         10        18.97         52        43.03   
##   4       90         25        28.03         65        61.97   
##   5       91         25        29.28         66        61.72   
##   6       93         41        31.60         52        61.40   
##   7       91         37        32.73         54        58.27   
##   8       97         41        38.29         56        58.71   
##   9       87         61        42.30         26        44.70   
##  10       92         65        65.86         27        26.14   
## --------------------------------------------------------------
## 
##      Goodness of Fit Test      
## ------------------------------
## Chi-Square    DF    Pr &gt; ChiSq 
## ------------------------------
##  37.1859      8       0.0000   
## ------------------------------</code></pre>
<p><br><br></p>
</div>
<div id="assessing-model-residuals" class="section level3" number="14.2.8">
<h3>
<span class="header-section-number">14.2.8</span> Assessing model residuals<a class="anchor" aria-label="anchor" href="#assessing-model-residuals"><i class="fas fa-link"></i></a>
</h3>
<p>A binned residual plot, available in the arm package, is a good way to see the residuals - to use you will need to install/load the arm package From the documentation:</p>
<blockquote>
<p><em>“In logistic regression, as with linear regression, the residuals can be defined as observed minus expected values. The data are discrete and so are the residuals. As a result, plots of raw residuals from logistic regression are generally not useful. The binned residuals plot instead, after dividing the data into categories (bins) based on their fitted values, the average residual versus the average fitted value for each bin.”</em></p>
</blockquote>
<div class="sourceCode" id="cb291"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://CRAN.R-project.org/package=arm">arm</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/arm/man/binnedplot.html">binnedplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span>, </span>
<span>           <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">model.logistic</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span>, </span>
<span>           nclass <span class="op">=</span> <span class="cn">NULL</span>, </span>
<span>           xlab <span class="op">=</span> <span class="st">"Expected Values"</span>, </span>
<span>           ylab <span class="op">=</span> <span class="st">"Average residual"</span>, </span>
<span>           main <span class="op">=</span> <span class="st">"Binned residual plot"</span>, </span>
<span>           cex.pts <span class="op">=</span> <span class="fl">0.8</span>, </span>
<span>           col.pts <span class="op">=</span> <span class="fl">1</span>, </span>
<span>           col.int <span class="op">=</span> <span class="st">"gray"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-13-1.png" width="672"></div>
<div id="alternative-plots" class="section level4" number="14.2.8.1">
<h4>
<span class="header-section-number">14.2.8.1</span> Alternative plots<a class="anchor" aria-label="anchor" href="#alternative-plots"><i class="fas fa-link"></i></a>
</h4>
<p>We can also use plots from the blorr package. These are harder to interpret and go a little beyond this course. I suggest this link for the code <a href="https://cran.r-project.org/web/packages/blorr/vignettes/introduction.html" class="uri">https://cran.r-project.org/web/packages/blorr/vignettes/introduction.html</a> and for the interpretation: <a href="https://bookdown.org/jefftemplewebb/IS-6489/logistic-regression.html" class="uri">https://bookdown.org/jefftemplewebb/IS-6489/logistic-regression.html</a></p>
<div class="sourceCode" id="cb292"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://blorr.rsquaredacademy.com/">blorr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://blorr.rsquaredacademy.com/reference/blr_plot_diag_influence.html">blr_plot_diag_influence</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-14-1.png" width="672"></div>
<p>or simply</p>
<div class="sourceCode" id="cb293"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">model.logistic</span><span class="op">)</span></span></code></pre></div>
<p><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-15-1.png" width="672"><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-15-2.png" width="672"><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-15-3.png" width="672"><img src="in_04-Tutorial14_GLM_files/figure-html/unnamed-chunk-15-4.png" width="672"></p>
<p><br><br></p>
</div>
</div>
<div id="interactions-with-other-predictors" class="section level3" number="14.2.9">
<h3>
<span class="header-section-number">14.2.9</span> Interactions with other predictors<a class="anchor" aria-label="anchor" href="#interactions-with-other-predictors"><i class="fas fa-link"></i></a>
</h3>
<p>You can also use this plot to look at interactions and confounding variables with other predictors.Here’s a classic example on diabetes to give you a better sense of the plot, as discussed in <a href="https://bookdown.org/jefftemplewebb/IS-6489/logistic-regression.html#assessing-logistic-model-performance" class="uri">https://bookdown.org/jefftemplewebb/IS-6489/logistic-regression.html#assessing-logistic-model-performance</a></p>
<div class="inline-figure"><img src="index_images/im_T14_LogisticInmteraction.png" style="width:80.0%"></div>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="S.Tutorial_Transformations.html"><span class="header-section-number">13</span> Transformations</a></div>
<div class="next"><a href="basic-model-comparisons.html"><span class="header-section-number">15</span> Basic model comparisons</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#S.Tutorial_GLM"><span class="header-section-number">14</span> GLM - Logistic Regression</a></li>
<li><a class="nav-link" href="#great-r-tutorial"><span class="header-section-number">14.1</span> Great R Tutorial</a></li>
<li>
<a class="nav-link" href="#setting-up-the-dataexample"><span class="header-section-number">14.2</span> Setting up the data/example</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#setting-up-categorical-columns"><span class="header-section-number">14.2.1</span> Setting up categorical columns</a></li>
<li><a class="nav-link" href="#filtering-data-exploratory-plots"><span class="header-section-number">14.2.2</span> Filtering data &amp; exploratory plots</a></li>
<li><a class="nav-link" href="#fiting-a-logistic-model"><span class="header-section-number">14.2.3</span> Fiting a logistic model</a></li>
<li><a class="nav-link" href="#model-summary"><span class="header-section-number">14.2.4</span> Model summary</a></li>
<li><a class="nav-link" href="#predicting-new-values-and-visualising-results"><span class="header-section-number">14.2.5</span> Predicting new values and visualising results</a></li>
<li><a class="nav-link" href="#wald-test-for-significance"><span class="header-section-number">14.2.6</span> Wald test for significance</a></li>
<li><a class="nav-link" href="#goodness-of-fit"><span class="header-section-number">14.2.7</span> Goodness of fit</a></li>
<li><a class="nav-link" href="#assessing-model-residuals"><span class="header-section-number">14.2.8</span> Assessing model residuals</a></li>
<li><a class="nav-link" href="#interactions-with-other-predictors"><span class="header-section-number">14.2.9</span> Interactions with other predictors</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>STAT462 Lab Book 2024</strong>" was written by Dr Helen Greatrex. It was last built on 2024-04-24.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
